version: "3.8"

services:
  postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    ports: [] # Don't expose DB port in production

  backend:
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DB_PORT=5432
      - PORT=5002
    ports: [] # Don't expose backend port directly
    volumes: [] # No volume mounting in production

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=/api
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
    ports: [] # Don't expose frontend port directly
    volumes: [] # No volume mounting in production

  nginx:
    ports:
      - "80:80"
      - "443:443" # For SSL in production

volumes:
  postgres_prod_data:
